# http://wiki.ros.org/base_local_planner
TrajectoryPlannerROS:
   max_vel_x: 0.1
   min_vel_x: 0.02
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   max_vel_theta: 2.0
   min_vel_theta: -2.0  # Setting this negative is critical or the robot will only turn one way
   min_in_place_vel_theta: 0.2
   min_in_place_rotational_vel: 0.2     # old parameter name
   escape_vel: 0.0                      # Set to 0.0 to prevent backing up
   acc_lim_x:                    1.0 
   acc_lim_y:                    0.0    # 0 for non-holonomic robot
   acc_lim_theta:                2.0

   holonomic_robot: false
   yaw_goal_tolerance:        0.3  # 17 degrees
   xy_goal_tolerance:         0.15 # 15 cm (6 inches)
   latch_xy_goal_tolerance: false
   pdist_scale: 0.4
   gdist_scale: 0.8
   occdist_scale: 0.01

   meter_scoring: true

   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   oscillation_reset_dist: 0.25 # used to be 0.05
   publish_cost_grid_pc: true
   prune_plan: true
   #escape_reset_theta: 1.1

   sim_time: 1.7
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 6
   vy_samples: 0  # zero for a differential drive robot
   vtheta_samples: 20
   dwa: true
   simple_attractor: false
